spring:
  application:
    name: claims-material
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.79.206:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.79.206:3306/claims?characterEncoding=UTF-8
    username: root
    password: root
server:
  port: 12000
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dm.claims.entity
  global-config:
      db-config:
        id-type: auto
logging:
  level:
    com.dm.claims.dao: debug